{
  "id": "m89nulzf-zasp",
  "errorLog": "prompt.service.js:486 \n GET http://localhost:5000/api/prompts/metadata/categories-tags 404 (Not Found)\n\nprompt.service.js:492 カテゴリー・タグ取得エラー: \nAxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}\nPromptList.js:65 メタデータ取得エラー: \nAxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}\nprompt.service.js:92 \n GET http://localhost:5000/api/prompts?page=1&limit=10&sort=updatedAt%3Adesc 404 (Not Found)\nprompt.service.js:486 \n GET http://localhost:5000/api/prompts/metadata/categories-tags 404 (Not Found)\nprompt.service.js:92 \n GET http://localhost:5000/api/prompts?page=1&limit=10&sort=updatedAt%3Adesc 404 (Not Found)\nprompt.service.js:98 プロンプト一覧取得エラー: \nAxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}\nPromptList.js:93 プロンプト一覧取得エラー: \nAxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}\nprompt.service.js:492 カテゴリー・タグ取得エラー: \nAxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}\nPromptList.js:65 メタデータ取得エラー: \nAxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}\nprompt.service.js:98 プロンプト一覧取得エラー: \nAxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}p://localhost:3000\n  On Your Network:  http://192.168.11.15:3000\n\nNote that the development build is not optimized.\nTo create a production build, use npm run build.\n\nwebpack compiled successfully\nProxy error: Could not proxy request /favicon.ico from localhost:3000 to http://localhost:3000.\nSee https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).\n\nProxy error: Could not proxy request /favicon.ico from localhost:3000 to http://localhost:3000.\nSee https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).\n\nProxy error: Could not proxy request /favicon.ico from localhost:3000 to http://localhost:3000.\nSee https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).\n\nProxy error: Could not proxy request /favicon.ico from localhost:3000 to http://localhost:3000.\nSee https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).\n\nProxy error: Could not proxy request /favicon.ico from localhost:3000 to http://localhost:3000.\nSee https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).GET http://localhost:3000/favicon.ico 500 (Internal Server Error)Understand this errorAI\nuser.service.js:51 \n            \n            \n           GET http://localhost:5000/api/users?page=1&limit=10&search=&role= 404 (Not Found)\ndispatchXhrRequest @ xhr.js:195\nxhr @ xhr.js:15\ndispatchRequest @ dispatchRequest.js:51\nPromise.then\n_request @ Axios.js:163\nrequest @ Axios.js:40\n__webpack_modules__../node_modules/axios/lib/core/Axios.js._utils_js__WEBPACK_IMPORTED_MODULE_3__.default.forEach.Axios.<computed> @ Axios.js:213\nwrap @ bind.js:5\ngetUsers @ user.service.js:51\nfetchUsers @ UserList.js:41\n(anonymous) @ UserList.js:34\ncommitHookEffectListMount @ react-dom.development.js:23189\ncommitPassiveMountOnFiber @ react-dom.development.js:24965\ncommitPassiveMountEffects_complete @ react-dom.development.js:24930\ncommitPassiveMountEffects_begin @ react-dom.development.js:24917\ncommitPassiveMountEffects @ react-dom.development.js:24905\nflushPassiveEffectsImpl @ react-dom.development.js:27078\nflushPassiveEffects @ react-dom.development.js:27023\ncommitRootImpl @ react-dom.development.js:26974\ncommitRoot @ react-dom.development.js:26721\nperformSyncWorkOnRoot @ react-dom.development.js:26156\nflushSyncCallbacks @ react-dom.development.js:12042\n(anonymous) @ react-dom.development.js:25690Understand this errorAI\nUserList.js:55 ユーザー取得エラー: Promise {<fulfilled>: Error: リクエスト処理中にエラーが発生しました\n    at UserService._handleError (http://localhost:3000/static/js/bundle.…}\noverrideMethod @ hook.js:608\nfetchUsers @ UserList.js:55\nawait in fetchUsers\n(anonymous) @ UserList.js:34\ncommitHookEffectListMount @ react-dom.development.js:23189\ncommitPassiveMountOnFiber @ react-dom.development.js:24965\ncommitPassiveMountEffects_complete @ react-dom.development.js:24930\ncommitPassiveMountEffects_begin @ react-dom.development.js:24917\ncommitPassiveMountEffects @ react-dom.development.js:24905\nflushPassiveEffectsImpl @ react-dom.development.js:27078\nflushPassiveEffects @ react-dom.development.js:27023\ncommitRootImpl @ react-dom.development.js:26974\ncommitRoot @ react-dom.development.js:26721\nperformSyncWorkOnRoot @ react-dom.development.js:26156\nflushSyncCallbacks @ react-dom.development.js:12042\n(anonymous) @ react-dom.development.js:25690Understand this errorAI\nuser.service.js:131 \n            \n            \n           GET http://localhost:5000/api/users/stats 404 (Not Found)\ndispatchXhrRequest @ xhr.js:195\nxhr @ xhr.js:15\ndispatchRequest @ dispatchRequest.js:51\nPromise.then\n_request @ Axios.js:163\nrequest @ Axios.js:40\n__webpack_modules__../node_modules/axios/lib/core/Axios.js._utils_js__WEBPACK_IMPORTED_MODULE_3__.default.forEach.Axios.<computed> @ Axios.js:213\nwrap @ bind.js:5\ngetUserStats @ user.service.js:131\nfetchUserStats @ UserList.js:64\n(anonymous) @ UserList.js:33\ncommitHookEffectListMount @ react-dom.development.js:23189\ncommitPassiveMountOnFiber @ react-dom.development.js:24965\ncommitPassiveMountEffects_complete @ react-dom.development.js:24930\ncommitPassiveMountEffects_begin @ react-dom.development.js:24917\ncommitPassiveMountEffects @ react-dom.development.js:24905\nflushPassiveEffectsImpl @ react-dom.development.js:27078\nflushPassiveEffects @ react-dom.development.js:27023\ncommitRootImpl @ react-dom.development.js:26974\ncommitRoot @ react-dom.development.js:26721\nperformSyncWorkOnRoot @ react-dom.development.js:26156\nflushSyncCallbacks @ react-dom.development.js:12042\n(anonymous) @ react-dom.development.js:25690Understand this errorAI\nUserList.js:67 ユーザー統計取得エラー: Promise {<fulfilled>: Error: リクエスト処理中にエラーが発生しました\n    at UserService._handleError (http://localhost:3000/static/js/bundle.…}\noverrideMethod @ hook.js:608\nfetchUserStats @ UserList.js:67\nawait in fetchUserStats\n(anonymous) @ UserList.js:33\ncommitHookEffectListMount @ react-dom.development.js:23189\ncommitPassiveMountOnFiber @ react-dom.development.js:24965\ncommitPassiveMountEffects_complete @ react-dom.development.js:24930\ncommitPassiveMountEffects_begin @ react-dom.development.js:24917\ncommitPassiveMountEffects @ react-dom.development.js:24905\nflushPassiveEffectsImpl @ react-dom.development.js:27078\nflushPassiveEffects @ react-dom.development.js:27023\ncommitRootImpl @ react-dom.development.js:26974\ncommitRoot @ react-dom.development.js:26721\nperformSyncWorkOnRoot @ react-dom.development.js:26156\nflushSyncCallbacks @ react-dom.development.js:12042\n(anonymous) @ react-dom.development.js:25690Understand this errorAI\nuser.service.js:51 \n            \n            \n           GET http://localhost:5000/api/users?page=1&limit=10&search=&role= 404 (Not Found)\ndispatchXhrRequest @ xhr.js:195\nxhr @ xhr.js:15\ndispatchRequest @ dispatchRequest.js:51\nPromise.then\n_request @ Axios.js:163\nrequest @ Axios.js:40\n__webpack_modules__../node_modules/axios/lib/core/Axios.js._utils_js__WEBPACK_IMPORTED_MODULE_3__.default.forEach.Axios.<computed> @ Axios.js:213\nwrap @ bind.js:5\ngetUsers @ user.service.js:51\nfetchUsers @ UserList.js:41\n(anonymous) @ UserList.js:34\ncommitHookEffectListMount @ react-dom.development.js:23189\ninvokePassiveEffectMountInDEV @ react-dom.development.js:25193\ninvokeEffectsInDev @ react-dom.development.js:27390\ncommitDoubleInvokeEffectsInDEV @ react-dom.development.js:27369\nflushPassiveEffectsImpl @ react-dom.development.js:27095\nflushPassiveEffects @ react-dom.development.js:27023\ncommitRootImpl @ react-dom.development.js:26974\ncommitRoot @ react-dom.development.js:26721\nperformSyncWorkOnRoot @ react-dom.development.js:26156\nflushSyncCallbacks @ react-dom.development.js:12042\n(anonymous) @ react-dom.development.js:25690Understand this errorAI\nUserList.js:55 ユーザー取得エラー: Promise {<fulfilled>: Error: リクエスト処理中にエラーが発生しました\n    at UserService._handleError (http://localhost:3000/static/js/bundle.…}\noverrideMethod @ hook.js:608\nfetchUsers @ UserList.js:55\nawait in fetchUsers\n(anonymous) @ UserList.js:34\ncommitHookEffectListMount @ react-dom.development.js:23189\ninvokePassiveEffectMountInDEV @ react-dom.development.js:25193\ninvokeEffectsInDev @ react-dom.development.js:27390\ncommitDoubleInvokeEffectsInDEV @ react-dom.development.js:27369\nflushPassiveEffectsImpl @ react-dom.development.js:27095\nflushPassiveEffects @ react-dom.development.js:27023\ncommitRootImpl @ react-dom.development.js:26974\ncommitRoot @ react-dom.development.js:26721\nperformSyncWorkOnRoot @ react-dom.development.js:26156\nflushSyncCallbacks @ react-dom.development.js:12042\n(anonymous) @ react-dom.development.js:25690Understand this errorAI\nuser.service.js:131 \n            \n            \n           GET http://localhost:5000/api/users/stats 404 (Not Found)\ndispatchXhrRequest @ xhr.js:195\nxhr @ xhr.js:15\ndispatchRequest @ dispatchRequest.js:51\nPromise.then\n_request @ Axios.js:163\nrequest @ Axios.js:40\n__webpack_modules__../node_modules/axios/lib/core/Axios.js._utils_js__WEBPACK_IMPORTED_MODULE_3__.default.forEach.Axios.<computed> @ Axios.js:213\nwrap @ bind.js:5\ngetUserStats @ user.service.js:131\nfetchUserStats @ UserList.js:64\n(anonymous) @ UserList.js:33\ncommitHookEffectListMount @ react-dom.development.js:23189\ninvokePassiveEffectMountInDEV @ react-dom.development.js:25193\ninvokeEffectsInDev @ react-dom.development.js:27390\ncommitDoubleInvokeEffectsInDEV @ react-dom.development.js:27369\nflushPassiveEffectsImpl @ react-dom.development.js:27095\nflushPassiveEffects @ react-dom.development.js:27023\ncommitRootImpl @ react-dom.development.js:26974\ncommitRoot @ react-dom.development.js:26721\nperformSyncWorkOnRoot @ react-dom.development.js:26156\nflushSyncCallbacks @ react-dom.development.js:12042\n(anonymous) @ react-dom.development.js:25690Understand this errorAI\nUserList.js:67 ユーザー統計取得エラー: Promise {<fulfilled>: Error: リクエスト処理中にエラーが発生しました\n    at UserService._handleError (http://localhost:3000/static/js/bundle.…}\noverrideMethod @ hook.js:608\nfetchUserStats @ UserList.js:67\nawait in fetchUserStats\n(anonymous) @ UserList.js:33\ncommitHookEffectListMount @ react-dom.development.js:23189\ninvokePassiveEffectMountInDEV @ react-dom.development.js:25193\ninvokeEffectsInDev @ react-dom.development.js:27390\ncommitDoubleInvokeEffectsInDEV @ react-dom.development.js:27369\nflushPassiveEffectsImpl @ react-dom.development.js:27095\nflushPassiveEffects @ react-dom.development.js:27023\ncommitRootImpl @ react-dom.development.js:26974\ncommitRoot @ react-dom.development.js:26721\nperformSyncWorkOnRoot @ react-dom.development.js:26156\nflushSyncCallbacks @ react-dom.development.js:12042\n(anonymous) @ react-dom.development.js:25690Understand this errorAI\nfavicon.ico:1 \n            \n            \n           GET http://localhost:3000/favicon.ico 500 (Internal Server Error)Understand this errorAI\n\n\nPromptList.js:93 プロンプト一覧取得エラー: \nAxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}",
  "status": "archived",
  "createdAt": "2025-03-15T03:42:03.723Z",
  "errorType": "接続エラー",
  "relatedFiles": [],
  "investigationStartTime": "2025-03-15T03:42:03.753Z"
}